services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www
    depends_on:
      - vite
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    expose:
      - "9000"

  nginx:
    image: nginx:stable
    container_name: laravel-nginx
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  vite:
    image: node:20
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
